projects:
  liv:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: jdrkj4ojpzcufkrtsccmgm3wze
      endpoints:
        prod: >-
          https://d5erxtlizzcu3drlqedndtdoaa.appsync-api.us-west-2.amazonaws.com/graphql
