// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:88c56278-e1f7-4509-b91e-4497188a1b8e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_iYL0ZqGSp",
    "aws_user_pools_web_client_id": "3btubva6d5mlp778109nuditfu",
    "oauth": {}
};


export default awsmobile;
