// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:61f7e98c-9ec8-471d-a8b6-369b8d5821e7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BFFuTF3P4",
    "aws_user_pools_web_client_id": "7stbs6f292fk56hjcpcdhm57uq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5u7et2kgufgcpe2rxuchlj7auq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
