// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
   "aws_project_region": "us-west-2",
   "aws_cognito_identity_pool_id": "us-west-2:88c56278-e1f7-4509-b91e-4497188a1b8e",
   "aws_cognito_region": "us-west-2",
   "aws_user_pools_id": "us-west-2_iYL0ZqGSp",
   "aws_user_pools_web_client_id": "3btubva6d5mlp778109nuditfu",
   "aws_dynamodb_all_tables_region": "us-west-2",
   "aws_dynamodb_table_schemas": [
       {
           "tableName": "livvyMessages-dev",
           "region": "us-west-2"
       },
       {
           "tableName": "livvyUsers-dev",
           "region": "us-west-2"
       }
   ],
   "aws_cloud_logic_custom": [
       {
           "name": "livvyAPI",
           "endpoint": "https://jofpgds5a6.execute-api.us-west-2.amazonaws.com/dev",
           "region": "us-west-2"
       }
   ]
};


export default awsmobile;
